initializr:
  bootVersions:
    - name: Enterprise 5.2.4
      id: 5.2.4.RELEASE
      default: true
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
  languages:
    - name: Java
      id: java
      default: true
  packagings:
    - name: Amp
      id: amp
      default: true
    - name: Jar
      id: jar

  types:
    - name: Alfred Gradle SDK Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: true
      action: /starter.zip
    - name: Alfresco Maven SDK Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: false
      action: /starter.zip


  dependencies:
    - name: Dynamic Extensions
      content:
      - name: Dynamic Extensions
        id: alfresco-dynamic-extensions-repo
        groupId: eu.xenit
        artifactId: alfresco-dynamic-extensions-repo
        version: 1.7.6.RELEASE
        description: Rapid development of Alfresco repository extensions in Java.